name: 'Sparky AI Alt Tags'
description: 'Install and configure base requirements for AI alt tags integration'
type: 'Site'

install:
  - ai_image_alt_text
config:
  import:
    ai_image_alt_text: '*'
